### ISSUE TITLE
gpu OOM occurs with a specific image

### ISSUE THREAD

**Issue by GeonYi** [2U1/Qwen2-VL-Finetune#88]
OOM (Out of Memory) occurred at a specific point during model training.

Upon checking the image, there was no significant difference compared to other images. The image has a resolution of approximately 500x800 and a DPI of around 72.

Through debugging, it was found that cu_seqlens in transformers increased abnormally. While it was typically within 50, it surged to nearly 800. Tracing the value's flow led to image_thw in data.py. However, I couldn't fully understand the logic, making it difficult for me to resolve the issue.

I trained a 2.5B 7B model on an H100 80GB GPU.
Even with all memory-related options turned off, the available VRAM should be sufficient for training.

Is there a possible solution for this?

**Comment by 2U1** [comment]
I've trained the vision-encoder alone and it takes a bit much memory with it.
But its strange that only the size of 500x800 takes too much. 

Could you check

```
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": your_image.png,
            }
        ]
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
len(inputs['input_ids'])
``` 

With this code and check how much the tokens are?

**Comment by GeonYi** [comment]
Thank you for your response.

The output tokens are 1273 tokens.

**Comment by GeonYi** [comment]
Thank you for your response.

The output tokens are 1273 tokens.

**Comment by 2U1** [comment]
Well that could take a bit much memmory but, it should be okay with it.
Maybe limiting the image size could be a bit useful. 

InternVL2.5 uses dynamic resoultion but the training code limits the image sizes as well.
InternVL2.5 -2B need 8*32GB of memory for full finetuning depite they are forcing the image sizes. (You can check out the info here https://internvl.readthedocs.io/en/latest/internvl2.5/finetune.html)


I'll make a code for resizing the image width and height.

**Comment by GeonYi** [comment]
I just confirmed that there was an issue with the image.

Among the training data, there was an image file with a resolution of 1200 dpi, which generated an extremely large token.

According to our intention, such images should be resized by max_pixel, but for some reason, it seems that max_pixel is not functioning properly. We resolved the issue by modifying the code to directly load the image, reduce the dpi, and pass the encoded value.

Once again, thank you for the code you provided.

**Comment by 2U1** [comment]
Thanks for letting me know.
I'll check again for modifying the token numbers with max_pixel. Also adding some args for adjusting width and height.

**Comment by GeonYi** [comment]
프로필을 확인하니 한국분 이셨군요!! 
좋은 코드 다시 감사드립니다.

**Comment by 2U1** [comment]
I've updated the code to explicitly set resized_height and resized_width for both images and videos.
